{% set name = "openssh" %}
{% set version = "9.3p1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/{{ name }}-{{ version }}.tar.gz
  sha256: e9baba7701a76a51f3d85a62c383a3c9dcd97fa900b859bc7db114c1868af8a8
  patches:
    - 0001-Set-strip-program-when-running-install.patch  # [linux]
    - 0002-ssh_compatible_openssl-for-openssl3.diff

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - zlib
    - libedit
    - libfido2
    - libxcrypt  # [linux]
    - krb5
    - openssl

test:
  commands:
    - ssh-keygen -t rsa -b 4096 -f id_rsa -P do-not-pass-passwords
    - type -f scp
    - type -f sftp
    - type -f ssh
    - type -f ssh-add
    - type -f ssh-agent
    - type -f sshd
    - type -f ssh-keygen
    - type -f ssh-keyscan

about:
  home: https://www.openssh.com/
  license: SSH-OpenSSH
  license_file: LICENCE
  summary: A suite of secure networking utilities based on the SSH protocol
  description: |
    OpenSSH is the premier connectivity tool for remote login with the SSH
    protocol. It encrypts all traffic to eliminate eavesdropping, connection
    hijacking, and other attacks. In addition, OpenSSH provides a large suite
    of secure tunneling capabilities, several authentication methods, and
    sophisticated configuration options.
  dev_url: https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/

extra:
  recipe-maintainers:
    - chrisburr
    - nehaljwani
